import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/components/providers";
import Appbar from "@/app/components/Appbar";
import SignInPanel from "@/app/components/signInPanel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Appbar>
             <SignInPanel />
          </Appbar>
          {children}
        </Providers>
      </body>
    </html>
  );
}
