import type { Metadata } from "next";
import Head from 'next/head'
import {ReactNode} from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import {Providers} from "@/app/components/providers";
import Appbar from "@/app/components/Appbar";
import SignInPanel from "@/app/components/signInPanel";

import {ToastContainer} from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
    <Head>
        <meta charSet="utf-8"/>
        <title>Apartments - Home page </title>
        <link rel="manifest" href="/favicon/manifest.json"/>
        <meta name="description" content="User Testing"/>
    </Head>
    <body className={inter.className}>
    <Providers>
          <Appbar>
             <SignInPanel />
          </Appbar>
          {children}
            <ToastContainer/>
        </Providers>
      </body>
    </html>
  );
}
